### ISSUE TITLE
EBS: Cannot find module debug

### ISSUE THREAD

**Issue by quiuquio** [mcolomer/any-file#2]
When deploying an application on Elastic Beanstalk the following error is show.

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/node_modules/any-file/lib/index.js:8:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Everything works before adding any-file.

**Comment by mcolomer** [comment]
Hi @quiuquio,

Debug package was added to package.json. Fixed additional issues related to packages dependencies.
Thanks for your feedback.

Regards,
