### ISSUE TITLE
Unable to transfer file from local to s3

### ISSUE THREAD

**Issue by Chayan-19** [mcolomer/any-file#9]
var anyfile = require(__dirname + "/..")();
var fromFile = "E://fonts.zip";
var toFile ="s3://my_aws_access_key_id:my_aws_secret_access_key@s3.amazon.com/my-bucket-name/fonts.zip";

try {
  anyfile.from(fromFile).to(toFile, function (err, res) {
    console.log(res);
    process.exit();
  });
} catch (err) {
  console.log(err);
}

I am using the above code to transfer files from my local machine to s3 bucket but I am gettting an error as:

PS D:\Divo-SFTP> node .\upload.js
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'D:\Divo-SFTP/..'
Require stack:
- D:\test\upload.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\test\upload.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\test\\upload.js' ]
}

Please help

**Comment by Chayan-19** [comment]
Was able to transfer files from my bucket to my local machine using this code:

var anyfile = require("any-file");
const AnyFile = require("any-file/lib");
var af = new AnyFile();
var fromFile ="s3://my_aws_access_key_id:my_aws_secret_access_key_id@s3.amazon.com/my-bucket-name/fonts.zip";
var toFile = "E://fonts2.zip";

try {
  af.from(fromFile).to(toFile, function (err, res) {
    console.log(res);
    process.exit();
  });
} catch (err) {
  console.log(err);
}

but when I interchanged the fromFile and toFile for tranfer from local machine to s3 I got this error

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.basename (path.js:671:5)
    at Object.__from [as from] (D:\test\node_modules\any-file\lib\index.js:646:29)
    at Object.<anonymous> (D:\test\upload.js:9:6)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

the parameters are:
var fromFile ="E://fonts2.zip";
var toFile = "s3://my_aws_access_key_id:my_aws_secret_access_key_id@s3.amazon.com/my-bucket-name/local/common/fonts2.zip";

**Comment by mcolomer** [comment]
Hi @Chayan-19 

It seems something related with the provided file.
I have no way to test it (I don't work on Windows sorry).

Can you try to put file fonts2.zip in the project folder and change your code this way
```
var fromFile =__dirname + "/fonts2.zip";
var toFile = "s3://my_aws_access_key_id:my_aws_secret_access_key_id@s3.amazon.com/my-bucket-name/local/common/fonts2.zip";
```
?

**Comment by Chayan-19** [comment]
Hi @mcolomer 

It turned out that I need to transfer contents from my s3 bucket to my sftp server that is hosted on aws itself.

using this code:

var anyfile = require("any-file");
const AnyFile = require("any-file/lib");
var af = new AnyFile();
var fromFile =
  "s3://my_aws_access_key_id:my_aws_secret_access_key_id@s3.amazon.com/my-bucket-name/fonts.zip";
var toFile = "sftp://username:password@ec2.amazon.com:/home/ec2-user/fonts.zip";

try {
  af.from(fromFile).to(toFile, function (err, res) {
    console.log(res);
    process.exit();
  });
} catch (err) {
  console.log(err);
}

It returned with a true value but didn't find the file in the server.

Also tried
var toFile = "sftp://username:password@ec2.amazon.com:/fonts.zip";
returned true but couldn't find the file.

Could you tell me whether the toFile is specified correctly or not?

**Comment by mcolomer** [comment]
Can you check sample
https://github.com/mcolomer/any-file/blob/master/samples/http2sftp.js
? 

Sftp is only supported for logins in your server adding a public key in the authorized_keys file (located at ~/. ssh folder)
